on:
  push:
    branches:
      - master

name: deploy-rest

jobs:
  deploy-rest:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_11
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Creating endpoints
        run: Rscript deploy.R
      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
