on:
  schedule:
    - cron: '0 * * * *'

name: slack-cron

jobs:
  slack-cron:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:RELEASE_3_11
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Running slackbot
        run: Rscript slackbot.R ${{ secrets.SLACK_WEBHOOK }}
