on: [push, pull_request]
    
name: Validate metadata

jobs:
  validate-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Run the validator
        run: |
            curl -L https://github.com/LTLA/acceptable-anime-gifs-validator/releases/download/latest/validator > validator
            chmod 755 validator
            ./validator -dir registry

      - name: Publish manifests
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          removeArtifacts: true
          artifacts: "gifs.json,shows.json"
          name: latest
          tag: latest
          body: "Formatted manifests for all GIFs and shows."
